# servarr
---
version: "3.7"

services:

  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    environment:
      PUID: 1031
      PGID: 100
      TZ: Europe/Amsterdam
      DELUGE_LOG_LEVEL: info
    volumes:
      - /volume2/docker/deluge:/config
      - /volume2/torrents:/downloads
    ports:
      - 8112:8112
      - 16881:6881
      - 16881:6881/udp
    restart: unless-stopped


  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-info}
      LOG_HTML: ${LOG_HTML:-false}
      CAPTCHA_SOLVER: ${CAPTCHA_SOLVER:-none}
      TZ: Europe/Amsterdam
    ports:
      - ${PORT:-8191}:8191
    restart: unless-stopped 

  maintainerr:
    image: ghcr.io/jorenn92/maintainerr:latest
    container_name: maintainerr
    user: 1030:100
    volumes: 
      - /volume2/docker/maintainerr:/opt/data
    environment:
      TZ: Europe/Amsterdam
    ports:
      - 6246:6246
    restart: unless-stopped

  prowlarr:
    image: linuxserver/prowlarr:develop
    container_name: prowlarr
    restart: unless-stopped
    ports:
      - 9696:9696
    cap_add:
      - NET_ADMIN
    environment:
      PUID: 1031
      PGID: 100
      TZ: Europe/Amsterdam
    volumes:
      - /volume2/docker/prowlarr:/config
      - /volume2/torrents/watch_folder:/downloads
  
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      PUID: 1031
      PGID: 100
      TZ: Europe/Amsterdam
    volumes:
      - /volume2/docker/sonarr:/config
      - /volume2/torrents:/downloads
      - /volume4/tv:/tv
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      PUID: 1031
      PGID: 100
      TZ: Europe/Amsterdam
    volumes:
      - /volume2/docker/radarr:/config
      - /volume2/torrents:/downloads
      - /volume4/films/1080p:/films
    ports:
      - 7878:7878
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      PUID: 1031
      PGID: 100
      TZ: Europe/Amsterdam
    volumes:
      - /volume2/docker/bazarr:/config
      - /volume4/films/1080p:/movies #optional
      - /volume4/tv:/tv #optional
    ports:
      - 6767:6767
    restart: unless-stopped